server:
  port: 10802

logging:
  level:
    web: INFO
    org:
      springframework: INFO

game:
  config:
    max-user-per-session: 5
    words-lower-count: 40

retry:
  maxAttempt: 2
  maxDelay: 1000

spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/typing_racer
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    add-properties: false

third-party:
  content:
    base-url: https://dog-api.kinduff.com
    api: ${third-party.content.base-url}/api/facts
    limit: 5
