server:
  port: 10802

logging:
  level:
    web: DEBUG

game:
  config:
    max-user-per-session: 5

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/typing_racer
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    add-properties: false